repositories:
  remote:
   - https://repo.maven.apache.org/maven2

artifacts:
  jsinterop_base: com.google.jsinterop:base:jar:1.0.0

  elemental2_core: org.realityforge.com.google.elemental2:elemental2-core:jar:2.25
  elemental2_dom: org.realityforge.com.google.elemental2:elemental2-dom:jar:2.25
  elemental2_promise: org.realityforge.com.google.elemental2:elemental2-promise:jar:2.25
  elemental2_webstorage: org.realityforge.com.google.elemental2:elemental2-webstorage:jar:2.25

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1
  gwt_user: org.realityforge.com.google.gwt:gwt-user:jar:2.8.2-v20191108
  gwt_dev: org.realityforge.com.google.gwt:gwt-dev:jar:2.8.2-v20191108
